server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db?createDatabaseIfNotExist=true
    username: root
    password: 7978@Rajaman
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.orderplatform.notification.kafka.event"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.orderplatform.notification.kafka.event.OrderCreatedEvent

kafka:
  topic:
    order-events: order-events

jwt:
  secret: change-this-secret-in-real-deployments-minimum-256-bits-long

cache:
  ttl:
    notification-minutes: 10

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.orderplatform.notification: DEBUG
