spring:
  datasource:
    url: jdbc:mysql://mysql:3306/order_db?createDatabaseIfNotExist=true
  data:
    redis:
      host: redis
  kafka:
    bootstrap-servers: kafka:29092

product-service:
  url: http://product-service:8082
